# Generated by Django 5.2.7 on 2025-10-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_image_url_card_image_url_large_card_abilities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='market_url',
        ),
        migrations.AddField(
            model_name='card',
            name='market_url_cardmarket',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='market_url_tcgplayer',
            field=models.URLField(blank=True, null=True),
        ),
    ]
