# Generated by Django 5.2.7 on 2025-10-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_card_market_url_card_market_url_cardmarket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='cardcondition',
            options={'verbose_name': 'Card Condition', 'verbose_name_plural': 'Card Conditions'},
        ),
        migrations.AlterModelOptions(
            name='cardset',
            options={'verbose_name': 'Card Set', 'verbose_name_plural': 'Card Sets'},
        ),
        migrations.AlterModelOptions(
            name='generation',
            options={'verbose_name': 'Generation', 'verbose_name_plural': 'Generations'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'User Address', 'verbose_name_plural': 'User Addresses'},
        ),
        migrations.AlterModelTable(
            name='card',
            table='store_card',
        ),
        migrations.AlterModelTable(
            name='cardcondition',
            table='store_cardcondition',
        ),
        migrations.AlterModelTable(
            name='cardset',
            table='store_cardset',
        ),
        migrations.AlterModelTable(
            name='generation',
            table='store_generation',
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='store_inventory',
        ),
        migrations.AlterModelTable(
            name='language',
            table='store_language',
        ),
        migrations.AlterModelTable(
            name='order',
            table='store_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='store_orderitem',
        ),
        migrations.AlterModelTable(
            name='user',
            table='store_user',
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table='store_useraddress',
        ),
    ]
